 console.log(`================= OC Assignment =================`);
 var a1= 0;
 var a2= '';
 var result= a1==a2;
 console.log(`1) Result of (0 == '') -: ${result}`);
 var a1= 0;
 var a2= '0';
 var result= a1==a2;
 console.log(`2) Result of (0 == '0') -: ${result}`);
 var a1= 0;
 var a2= false;
 var result= a1==a2;
 console.log(`3) Result of (0 == false) -: ${result}`);
 var a1= null;
 var a2= undefined;
 var result= a1==a2;
 console.log(`4) Result of (0 == undefined) -: ${result}`);
 var a1= 1;
 var a2= [1];
 var result= a1==a2;
 console.log(`5) Result of (0 == [1]) -: ${result}`);
 var a1= 1;
 var a2= true;
 var result= a1==a2;
 console.log(`6) Result of (0 == true) -: ${result}`);
 var a1= 1;
 var a2= '1';
 var result= a1==a2;
 console.log(`7) Result of (0 == '1') -: ${result}`);